In [1]:
from Solver import Solver
import numpy as np
from Brands import Brands
from Analyzer import Analyzer

my_sector = "Vodites" 

sol = Solver(sector=my_sector) 
brd = Brands(sector=my_sector)
an = Analyzer(sector=my_sector, last_period=7)

df_semantic = brd.df_segments_semantic
df_semantic = df_semantic.replace({"Segment":{"Early Adopters":"Adopters"}})


features = brd.df_brands_physical
features

d:\Uni\Anno III\UCSD\112\Markstrat\Code\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Attributes file:./Attributes/Vodites/attributes_Vodites_7.json
Vodites
./Exports/TeamExport_A46051_Alpha_M_Period 7.xlsx loaded
Vodites
./Exports/TeamExport_A46051_Alpha_M_Period 7.xlsx loaded
No weights provided

,Resolution,Energy Efficiency,Carbon Footprint,Connectivity,No. of Apps,Rec. retail price,Base Cost
MARKET : Vodites,,,,,,,
MEOW,63,35,31,7,54,671,248
REEGO,75,43,30,8,48,700,282
TENOR,47,50,45,5,15,600,193

In [2]:
brd.df_brands_semantic

,Resolution,Energy Efficiency,Carbon Footprint,Connectivity,No. of Apps,Price
MARKET : Vodites,,,,,,
MEOW,4.29,2.94,4.56,4.52,4.14,5.37
REEGO,5.24,2.81,4.41,4.86,3.64,5.33
TENOR,2.91,3.36,6.39,2.89,1.58,4.83

In [3]:
brd.df_segments_semantic

,Segment,Period,Resolution,Energy Efficiency,Carbon Footprint,Connectivity,No. of Apps,Price
Index,,,,,,,,
Adopters_7,Adopters,7,4.98,4.28,4.73,4.63,4.44,5.16
Followers_7,Followers,7,4.37,4.76,2.78,3.88,3.77,4.48
Innovators_7,Innovators,7,5.38,3.7,4.07,5.23,3.87,5.5
Early Adopters_6,Adopters,6,4.88,4.23,4.76,4.47,4.43,5.26
Followers_6,Followers,6,4.13,4.72,2.95,3.77,3.65,4.53
Innovators_6,Innovators,6,5.31,3.57,4.14,5.13,3.83,5.84
Early Adopters_5,Adopters,5,4.73,4.15,4.82,4.25,4.39,5.32
Followers_5,Followers,5,3.86,4.69,3.14,3.67,3.52,4.59
Innovators_5,Innovators,5,5.23,3.45,4.21,5.03,3.78,6.05
Early Adopters_4,Adopters,4,4.54,4.05,4.88,3.97,4.34,5.43
Followers_4,Followers,4,3.45,4.53,3.35,3.29,3.33,4.7
Innovators_4,Innovators,4,5.14,3.33,4.28,4.93,3.74,6.15
Early Adopters_3,Adopters,3,4.45,4,4.9,3.85,4.3,5.5
Followers_3,Followers,3,3.25,4.45,3.4,3.1,3.25,4.75
Innovators_3,Innovators,3,5.05,3.25,4.3,4.75,3.7,6.25

## FC

In [4]:
df_sem_fc = an.forecast_df(brd.df_segments_semantic, steps=2)
df_sem_fc

,Period,Segment,Resolution,Energy Efficiency,Carbon Footprint,Connectivity,No. of Apps,Price
Innovators_9,9,Innovators,5.52,3.96,3.93,5.43,3.95,4.82
Adopters_9,9,Adopters,5.18,4.38,4.67,4.95,4.46,4.96
Followers_9,9,Followers,4.85,4.84,2.44,4.1,4.01,4.38
Innovators_8,8,Innovators,5.45,3.83,4.0,5.33,3.91,5.16
Followers_8,8,Followers,4.61,4.8,2.61,3.99,3.89,4.43
Adopters_8,8,Adopters,5.08,4.33,4.7,4.79,4.45,5.06
Innovators_7,7,Innovators,5.38,3.7,4.07,5.23,3.87,5.5
Adopters_7,7,Adopters,4.98,4.28,4.73,4.63,4.44,5.16
Followers_7,7,Followers,4.37,4.76,2.78,3.88,3.77,4.48
Adopters_6,6,Adopters,4.88,4.23,4.76,4.47,4.43,5.26
Followers_6,6,Followers,4.13,4.72,2.95,3.77,3.65,4.53
Innovators_6,6,Innovators,5.31,3.57,4.14,5.13,3.83,5.84
Adopters_5,5,Adopters,4.73,4.15,4.82,4.25,4.39,5.32
Followers_5,5,Followers,3.86,4.69,3.14,3.67,3.52,4.59
Innovators_5,5,Innovators,5.23,3.45,4.21,5.03,3.78,6.05
Innovators_4,4,Innovators,5.14,3.33,4.28,4.93,3.74,6.15
Followers_4,4,Followers,3.45,4.53,3.35,3.29,3.33,4.7
Adopters_4,4,Adopters,4.54,4.05,4.88,3.97,4.34,5.43
Followers_3,3,Followers,3.25,4.45,3.4,3.1,3.25,4.75
Innovators_3,3,Innovators,5.05,3.25,4.3,4.75,3.7,6.25
Adopters_3,3,Adopters,4.45,4,4.9,3.85,4.3,5.5

In [5]:
rel_imp = brd.rel_importance_features
rel_imp

array([0.1735294117647059, 0.14411764705882354, 0.06470588235294118,
       0.29411764705882354, 0.08823529411764706, 0.23529411764705882],
      dtype=object)

In [7]:
followers = df_sem_fc[(df_sem_fc["Segment"]=="Followers")*(df_sem_fc["Period"]==7)]
#res = sol.find_optimum(sector="Vodites", ideal_semantic=followers, ideal_mds=[0,0,0],semantic_weights=rel_imp, error_weights=[1,0])

In [14]:
miao = brd.get_features("MEOW").drop(labels=["Base Cost"], axis=1).values.flatten()

miao_sem = brd.get_semantic("MEOW")

miao_sem

,Resolution,Energy Efficiency,Carbon Footprint,Connectivity,No. of Apps,Price
MARKET : Vodites,,,,,,
MEOW,4.29,2.94,4.56,4.52,4.14,5.37

In [ ]:
#res = sol.find_optimum(sector="Vodites", ideal_semantic=adopters_1, ideal_mds=[0,0,0],semantic_weights=rel_imp, error_weights=[1,0])

In [ ]:
an.compute_contribution(536, 306, [1/3,1/3,1/3])

33